# -*- coding: utf-8 -*-
"""lesen-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYkI-dhde6hLhqMPI5or13TF7U6vd8St
"""

import random as r

  prizes = ["дешовая машина OPEL GOLDE","носки","игровая приставака PS1","частный самолет (с экипажом и бабкой )","пупок"]
  print(prizes[r.randint(0,len(prizes) -1)])

import random as r

variants = ["Камень","Ножницы","Бумага"]

while True:

 player = input("Введите выбор: ")

 index = r.randint(0,len(variants) -1)
 computer = variants[index]

 print("Computer:",computer)

if player == "камень":
 if computer == "ножницы":
    print("Player wins")
elif player == "бумага":
 if computer == "камень":
    print("Player wins")
elif player == "ножницы":
 if computer == "бумага":
    print("Player wins")
elif player == computer:
  print("Draw!")
else:
  print("Computer Wins!")

sceneStart1='''
=======================================================================000000000
========XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX===00000000
========X...........................................................X=====000000
=~~=====X...........................................................X===========
~~~~~~==X...........................................................X===========
~~~~~~~=X.....XXXXXXXXXXXXXXXXX.....................................X===========
========X.....X     XX XX     X.....................................X===========
========X.....X    XXXXXXX    X.....................................X====~~=====
========X.....X     XXXXX     X.....................................X===~~~=====
========X.....XXXXXXXXXXXXXXXXX.............XXXXXXXXXXXXX...........X=~~~~~=====
========X...................................X...........X...........X===========
========X...................................X...........X...........X===========
========X...................................X...........X...........X===========
========X...................................X......XX...X...........X===========
========X...................................X......XX...X...........X===========
========X....XXXXXXXXXXXXXXXXXXXXXXX........X...........X...........X===========
========X......XXXXXXXXXXXXXXXXXXX..........X...........X...........X===========
========X......X..X..........X...X..........X...........X...........X===========
========X......X..XX.........X...X..........X...........X...........X===========
@@@@@@@@X......XXXXXXXXXXXXXXXXXXX..........XXXXXXXXXXXXX...........X@@@@@@@@@@@
@@@@@@@@XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
'''

playerName = input("Введите ваше имя: ")

print("Привет ", playerName + "!")

key = False

while True:
  print(sceneStart1)
  print("Вы появляетесь в странной комнате , в ней есть дверь,стол и жуткая картина!")
  print("1.Подойти к столу")
  print("2.Открыть дверь.")

  vibor = input("Ваш выбор: ")
  vibor = int(vibor)



  if vibor == 1:
    print("На столе лежит ключ.Взять?")
    print("1.Да.")
    print("2.Нет.")

    vibor = input("Ваш выбор: ")
    vibor = int(vibor)

    if vibor == 1:
      print("Взяли ключ.")
      Key = True
      input("Нажмите Enter")
    elif vibor == 2:
      print("Ключ остался на месте.")
      input("Нажмите Enter")

  elif vibor == 2:
    if Key == False:
      print("Дверь не открывается.")
      input("Нажмите Enter")
    elif Key == True:
      print("Дверь открылась.")
      print("Вы входите в другую комнату и на вас наподает Чулик")
      print("1.Банановая кожура")
      print("2.Убежать в предидущую комнату")

      vibor = input("Ваш выбор:")
      vibor = int(vibor)
      if vibor == 1:
        print("Банановая кожура пропала")
        print("ПЛОХАЯ КОНЦОВКА")
        break
      if vibor == 2:
        print("Вы кинули картинку и все круто вы победили !")
        print("ХОРОШАЯ КОНЦОВКА!")
        break